### ISSUE TITLE
Error trying to render any flow.

### ISSUE THREAD

**Issue by all2human** [toddhalfpenny/sfflowvisualiser-vscode#22]
4-01-26 08:49:19.141 [error] TypeError: Cannot read properties of undefined (reading 'targetReference')
	at c:\Users\852777\.vscode\extensions\toddhalfpenny.sfflowvisualiser-0.2.2\out\extension.js:21:128
	at new Promise (<anonymous>)
	at sr (c:\Users\852777\.vscode\extensions\toddhalfpenny.sfflowvisualiser-0.2.2\out\extension.js:18:73)
	at c:\Users\852777\.vscode\extensions\toddhalfpenny.sfflowvisualiser-0.2.2\out\extension.js:15:11

**Comment by all2human** [comment]
Maybe the problem is with flows that have a scheduled path? I was able to open flows without a scheduled path.

**Comment by toddhalfpenny** [comment]
Hey @all2human , apologies for the delay here... seems like I thought I'd be notified when issues were created (perhaps they're going into my spam).

I've actually just had a ping from someone on Linkedn with this issue (that brought me here to raise one) and this does appear to be related to that.
I have a fix I hope for this issue... but would you also mind sharing your flow XML (happy for you to contact me direct on this).
